{% set name = "resdk" %}
{% set version = "16.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/resdk-{{ version }}.tar.gz
  sha256: 6424cc0c7584f95f6738cbccc98e83902377438881d435776a7b19a6ea458f7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - aiohttp
    - chardet <=4.0,>=2.0
    - openpyxl
    - pandas >=1.0.0
    - python >=3.6
    - pytz >=2018.4
    - requests >=2.6.0
    - slumber >=0.7.1
    - tqdm
    - tzlocal >=1.5.1
    - wrapt
    - xlrd
    - boto3
    - numpy
    - mypy-boto3-s3
    - botocore
    - boto3-stubs

test:
  imports:
    - resdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/genialis/resolwe-bio-py
  summary: Resolwe SDK for Python
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Resolwe SDK for Python supports interaction with Resolwe server and its extension Resolwe Bioinformatics. You can use it to upload and inspect biomedical data sets, contribute annotations, run analysis, and write pipelines.
  doc_url: https://resdk.readthedocs.io/en/latest/
  dev_url: https://github.com/genialis/resolwe-bio-py

extra:
  recipe-maintainers:
    - HeavyTony2
