{% set name = "resdk" %}
{% set version = "21.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/resdk-{{ version }}.tar.gz
  sha256: 4a8348dfd6776a9ddee42effefd1c060be7940ec1b33f3b867a231d476f0459c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python =3.9 #Just for the building part
    - setuptools >=64.0.0
    - setuptools-scm >=6.4.0
    - pip
  run:
    - python <3.12
    - aiohttp >=3.8.5,<3.9.dev0
    - requests >=2.6.0
    - slumber >=0.7.1
    - wrapt
    - pytz >=2018.4
    - tzlocal >=1.5.1
    - pandas >=1.0.0
    - tqdm
    - openpyxl
    - xlrd
    - boto3 >=1.24,<2.dev0
    - boto3-stubs >=1.24,<2.dev0
    - importlib-metadata
    - mypy-boto3-s3 #not listed in toml file, but required at testing
    - packaging
    - urllib3 >=2
    
test:
  imports:
    - resdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/genialis/resolwe-bio-py
  summary: Resolwe SDK for Python
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Resolwe SDK for Python supports interaction with Resolwe server and its extension Resolwe Bioinformatics. You can use it to upload and inspect biomedical data sets, contribute annotations, run analysis, and write pipelines.
  doc_url: https://resdk.readthedocs.io/en/latest/
  dev_url: https://github.com/genialis/resolwe-bio-py

extra:
  recipe-maintainers:
    - HeavyTony2
